/* src/content/missions.js  Team Mission puzzles: each participant/subgroup gets one clue; the team solves together */
(function () {
  "use strict";
  window.TCL.Content.registerBank("missions", [
    { text: "The Missing Laptop", brief: "Five colleagues shared one laptop on Monday: Sam, Priya, Tom, Grace and Mei. Each of them used it exactly once, one after another. Work out the full order, and say who used it last.", clues: ["Sam used it at some point before Priya.", "Mei used it last thing before going home.", "Exactly one person used it in between Sam and Grace.", "Priya used it before Grace.", "Sam used it at some point before Tom."], solution: "Sam, Priya, Grace, Tom, Mei, so Mei used it last. Mei is fixed at the end, and Sam before Priya before Grace with exactly one person between Sam and Grace forces Sam, Priya and Grace to sit in three consecutive slots. That leaves only two possible starting points, and the one where Tom comes before Sam is ruled out by the last clue.", hints: ["Start with the one person whose position is stated outright.", "If Sam comes before Priya and Priya comes before Grace, how far apart can Sam and Grace be?", "Once Sam, Priya and Grace are consecutive, try both starting slots and check where Tom lands."], category: "Logic", difficulty: 1 },

    { text: "Which Meeting Room", brief: "The workshop is booked into one of eight rooms, but the invite lost the room name. Here is the room list.\nBanyan: floor 2, seats 8, projector, window, whiteboard, video call kit.\nCoral: floor 3, seats 10, no projector, window, whiteboard, video call kit.\nDelta: floor 2, seats 6, projector, no window, whiteboard, video call kit.\nEverest: floor 4, seats 8, projector, window, whiteboard, video call kit.\nFig: floor 3, seats 12, projector, window, whiteboard, video call kit.\nHarbour: floor 2, seats 10, projector, window, no whiteboard, video call kit.\nIronbark: floor 3, seats 8, projector, window, whiteboard, no video call kit.\nJacaranda: floor 3, seats 12, no projector, window, whiteboard, video call kit.\nFind the room.", clues: ["The room has a projector.", "The room has a window.", "The room is not on floor 4.", "The room seats fewer than 12 people.", "The room has a whiteboard.", "The room has a video call kit."], solution: "Banyan. The projector rules out Coral and Jacaranda, the window rules out Delta, the floor rules out Everest, the seat count rules out Fig and Jacaranda, the whiteboard rules out Harbour, and the video call kit rules out Ironbark. Banyan is the only room left, and every clue is needed because each one is the only thing that rules out at least one room.", hints: ["Write the eight room names in a column and cross one off as each clue is read out.", "Several clues rule out only a single room, so read all six before deciding.", "Only one room has all four facilities, sits below floor 4, and seats fewer than twelve."], category: "Logic", difficulty: 1 },

    { text: "The Store Room Code", brief: "The store room keypad takes a four digit code and nobody wrote it down. Each person holds one fact about it. Work out the code.", clues: ["All four digits are different from each other.", "The code is an even number.", "The first digit is exactly twice the last digit.", "The third digit is exactly 3 more than the last digit.", "The second and third digits add up to 9."], solution: "8274. Call the last digit d. The code then reads 2d, then 6 minus d, then d plus 3, then d. The code is even so d is even, and doubling d has to stay a single digit, so d is 0, 2 or 4. Zero gives 0630 and two gives 4452, and both repeat a digit, so d is 4 and the code is 8274.", hints: ["Three of the clues describe other digits in terms of the last digit, so work backwards from that one.", "The last digit is even, and twice it still has to be a single digit.", "That leaves only three candidates for the last digit. Test each one against the repeated digit rule."], category: "Numbers", difficulty: 2 },

    { text: "Who Sits Where", brief: "Arjun, Grace, Jun and Lena each sit on a different floor: 2, 3, 4 or 5. Each of them gets to work a different way: train, bike, bus or on foot. Match every person to a floor and a way of getting in.", clues: ["Arjun sits two floors above Jun.", "The person who cycles sits on floor 3.", "Grace does not take the train.", "The person who walks in sits on floor 2, the lowest of the four.", "Grace sits on floor 4."], solution: "Lena is on floor 2 and walks, Jun is on floor 3 and cycles, Grace is on floor 4 and takes the bus, Arjun is on floor 5 and takes the train. Grace on floor 4 leaves floors 2, 3 and 5, and the only pair exactly two apart is Jun on 3 with Arjun on 5, so Lena takes floor 2. The floors then hand you the cyclist and the walker, and since Grace does not take the train she takes the bus and Arjun takes the train.", hints: ["Place the two clues that name a floor outright, then see which floors are left.", "Among the free floors, only one pair is exactly two apart.", "Once every floor is settled, two of the clues name the cyclist and the walker directly."], category: "Logic", difficulty: 2 },

    { text: "The Showcase Running Order", brief: "Five people present at the team showcase, one each at 9:00, 9:20, 9:40, 10:00 and 10:20. The presenters are Mei, Tom, Priya, Arjun and Lena. Work out who is on at each time.", clues: ["Mei presents at some point before Tom.", "Priya has the 9:40 slot.", "Mei does not present first.", "Arjun presents after Priya.", "There are exactly two presenters between Lena and Tom."], solution: "Lena at 9:00, Mei at 9:20, Priya at 9:40, Tom at 10:00 and Arjun at 10:20. Priya is fixed at 9:40 and Arjun has to follow her, so Arjun is at 10:00 or 10:20. Lena and Tom must be three slots apart, and the only arrangement that also leaves Mei a slot that is neither first nor after Tom is Lena at 9:00 with Tom at 10:00.", hints: ["Pin the slot you are handed, then work out which slots Arjun could possibly take.", "Two presenters between Lena and Tom means their slots are three apart. List every pair that far apart.", "Test both orders of Lena and Tom. One of them leaves Mei nowhere legal to stand."], category: "Schedule", difficulty: 2 },

    { text: "Quiz Night Scores", brief: "Four teams played quiz night: the Falcons, the Otters, the Pandas and the Yaks. The final scores were 12, 15, 18 and 21, one score per team. Work out who scored what.", clues: ["The Falcons scored more points than the Otters.", "The Pandas did not score 21.", "The team on 15 points was not the Falcons.", "The Falcons did not win.", "The Otters scored fewer points than the Pandas."], solution: "Falcons 18, Otters 12, Pandas 15, Yaks 21. The Falcons are not on 15 and did not win, so they are on 12 or 18, and because they beat the Otters they cannot be on the lowest score, which puts them on 18. The Pandas are not on 21, so the Pandas and the Otters hold 12 and 15, and the Otters scored fewer, giving the Otters 12, the Pandas 15 and the Yaks 21.", hints: ["Two of the clues say what the Falcons did not score. Start by crossing those off.", "The Falcons beat the Otters, so the Falcons cannot be on the lowest score either.", "Once the Falcons are placed, only two scores are left for the Pandas and the Otters."], category: "Numbers", difficulty: 2 },

    { text: "The New Floor Plan", brief: "Sam, Mei, Diego and Nadia have moved into the new office. Each has a different role (designer, analyst, engineer, writer), sits on a different floor (1, 2, 3 or 4) and brought a different lunch (salad, noodles, sandwich, curry). Work out all three facts for each person.", clues: ["The engineer sits two floors above Mei.", "Diego brought noodles.", "The person on floor 1 brought a sandwich.", "The writer sits one floor below the designer.", "Sam sits on floor 3.", "The person who brought salad sits on floor 4."], solution: "Mei is the writer on floor 1 with the sandwich, Diego is the designer on floor 2 with the noodles, Sam is the engineer on floor 3 with the curry, and Nadia is the analyst on floor 4 with the salad. Mei has to be on floor 1 or 2 for the engineer clue to work, and floor 2 fails because it forces Diego onto floor 1 or floor 4, where the lunch is already a sandwich or a salad. So Mei is on floor 1, the engineer is Sam on floor 3, the writer and designer take the neighbouring floors 1 and 2, and Nadia is left as the analyst on floor 4.", hints: ["Sam is on floor 3, so begin by testing which floors Mei could possibly be on.", "The engineer sits two floors above Mei and the writer sits directly below the designer. Those two facts compete for the same floors.", "Diego brought noodles, so he cannot be the person on floor 1 or the person on floor 4."], category: "Logic", difficulty: 3 },

    { text: "The Delivery Run", brief: "A van reaches its first office at 9:00 sharp and then visits five offices one after another, in some order. Time spent on site: Northgate 30 minutes, Riverside 20, Southbank 40, Eastwood 20, Westpark 30. Driving from any office to the next takes 15 minutes. Work out the order of the run and the time each visit begins.", clues: ["The van starts the day at Riverside.", "Northgate is not the last stop of the day.", "Exactly one stop comes between Westpark and Southbank.", "Eastwood is not the second stop.", "The last visit of the day begins at 11:50."], solution: "Riverside 9:00, Northgate 9:35, Southbank 10:20, Eastwood 11:15, Westpark 11:50. From 9:00 to 11:50 is 170 minutes, and 60 of those are the four drives, so the first four visits total 110 minutes. All five visits total 140 minutes, so the last stop is a 30 minute one, which is Northgate or Westpark. Northgate is ruled out, so Westpark is fifth, that puts Southbank third, and with Eastwood barred from second the order is fixed.", hints: ["Add up all five visit times and all four drives before you worry about the order.", "11:50 minus 9:00 is 170 minutes, and 60 of those minutes are spent driving.", "Only two offices have a 30 minute visit, and one of the two is ruled out from the last slot."], category: "Schedule", difficulty: 3 },
  ], [
    { key: "text", label: "Mission title", type: "text", required: true },
    { key: "brief", label: "Brief shown to everyone", type: "textarea", required: true },
    { key: "clues", label: "Clues (one per person or subgroup)", type: "list", required: true },
    { key: "solution", label: "Solution (facilitator only)", type: "textarea", required: true },
    { key: "hints", label: "Hints in order", type: "list", required: false },
  ]);
})();
