/* src/content/wyr.js  Would You Rather bank */
(function () {
  "use strict";
  window.TCL.Content.registerBank("wyr", [
    /* ---------- Funny (18) ---------- */
    { text: "Would you rather fight one horse sized duck or one hundred duck sized horses?", a: "One horse sized duck", b: "100 duck sized horses", category: "Funny", difficulty: 1 },
    { text: "Would you rather always enter a room by cartwheeling or always leave it walking backwards?", a: "Cartwheel in", b: "Walk out backwards", category: "Funny", difficulty: 2 },
    { text: "Would you rather have fingers as long as your legs or legs as short as your fingers?", a: "Very long fingers", b: "Very short legs", category: "Funny", difficulty: 1 },
    { text: "Would you rather sneeze glitter every single time or hiccup soap bubbles every single time?", a: "Glitter sneezes", b: "Bubble hiccups", category: "Funny", difficulty: 2 },
    { text: "Would you rather talk to animals but only about weather, or read minds but only when people are bored?", a: "Weather chat with animals", b: "Read bored minds", category: "Funny", difficulty: 3 },
    { text: "Would you rather have a permanent unicorn horn or a permanent tail you cannot hide?", a: "Unicorn horn", b: "Tail you cannot hide", category: "Funny", difficulty: 1 },
    { text: "Would you rather every food you eat taste like mango or every drink you sip taste like soup?", a: "Mango flavoured food", b: "Soup flavoured drinks", category: "Funny", difficulty: 2 },
    { text: "Would you rather speak only in rhyme or sing your last three words every time you talk?", a: "Speak in rhyme", b: "Sing the last words", category: "Funny", difficulty: 3 },
    { text: "Would you rather have a theme song play when you walk in or a narrator describe your whole day?", a: "Your own theme song", b: "A live narrator", category: "Funny", difficulty: 1 },
    { text: "Would you rather be five centimetres tall for a week or five metres tall for one day?", a: "Tiny for a week", b: "Giant for a day", category: "Funny", difficulty: 2 },
    { text: "Would you rather have hands where your feet are or feet where your hands are?", a: "Hands for feet", b: "Feet for hands", category: "Funny", difficulty: 2 },
    { text: "Would you rather ride a giant snail everywhere or a very fast and very rude ostrich?", a: "Giant snail", b: "Fast rude ostrich", category: "Funny", difficulty: 2 },
    { text: "Would you rather own a fridge that argues with you or a car that hums off key all day?", a: "Arguing fridge", b: "Off key humming car", category: "Funny", difficulty: 2 },
    { text: "Would you rather have to shout everything you say or whisper everything you say?", a: "Always shout", b: "Always whisper", category: "Funny", difficulty: 2 },
    { text: "Would you rather have a pet dinosaur the size of a cat or a pet cat the size of a dinosaur?", a: "Cat sized dinosaur", b: "Dinosaur sized cat", category: "Funny", difficulty: 1 },
    { text: "Would you rather teleport only to places you have already been or fly at walking speed?", a: "Limited teleporting", b: "Very slow flying", category: "Funny", difficulty: 2 },
    { text: "Would you rather every photo of you come out blurry or every video of you play in slow motion?", a: "Blurry photos", b: "Slow motion videos", category: "Funny", difficulty: 3 },
    { text: "Would you rather wear shoes two sizes too big forever or a hat two sizes too small forever?", a: "Oversized shoes", b: "Very tight hat", category: "Funny", difficulty: 2 },

    /* ---------- Casual (16) ---------- */
    { text: "Would you rather have unlimited free coffee for life or unlimited free public transport for life?", a: "Unlimited free coffee", b: "Unlimited free transport", category: "Casual", difficulty: 1 },
    { text: "Would you rather take a beach holiday every year or a mountain trek every year?", a: "Beach holiday", b: "Mountain trek", category: "Casual", difficulty: 2 },
    { text: "Would you rather never queue for anything again or never hunt for a parking spot again?", a: "No more queues", b: "No more parking hunts", category: "Casual", difficulty: 1 },
    { text: "Would you rather be given one extra hour every morning or one extra hour every night?", a: "Extra morning hour", b: "Extra night hour", category: "Casual", difficulty: 3 },
    { text: "Would you rather always know the perfect song for the moment or the perfect snack for the moment?", a: "The perfect song", b: "The perfect snack", category: "Casual", difficulty: 2 },
    { text: "Would you rather spend the evening with a great book or a great film?", a: "A great book", b: "A great film", category: "Casual", difficulty: 1 },
    { text: "Would you rather live somewhere sunny all year or somewhere that rains every evening?", a: "Sunny all year", b: "Rain every evening", category: "Casual", difficulty: 2 },
    { text: "Would you rather be able to speak every language or play every musical instrument?", a: "Every language", b: "Every instrument", category: "Casual", difficulty: 3 },
    { text: "Would you rather wake up early with no effort or stay up late with no effort?", a: "Easy early mornings", b: "Easy late nights", category: "Casual", difficulty: 1 },
    { text: "Would you rather have a home cinema in your place or a home library in your place?", a: "Home cinema", b: "Home library", category: "Casual", difficulty: 2 },
    { text: "Would you rather never lose your keys again or never lose a phone charger again?", a: "Keys always found", b: "Charger always found", category: "Casual", difficulty: 2 },
    { text: "Would you rather spend a free Saturday walking outdoors or cooking something new?", a: "Walking outdoors", b: "Cooking something new", category: "Casual", difficulty: 1 },
    { text: "Would you rather have a garden that thrives with no effort or a bookshelf that refills itself?", a: "Effortless garden", b: "Self refilling shelf", category: "Casual", difficulty: 2 },
    { text: "Would you rather remember every book you read or every conversation you have?", a: "Remember every book", b: "Remember every chat", category: "Casual", difficulty: 3 },
    { text: "Would you rather get free tickets to any concert or free tickets to any sports match?", a: "Any concert", b: "Any sports match", category: "Casual", difficulty: 2 },
    { text: "Would you rather have a kitchen that cleans itself or a laundry basket that folds everything?", a: "Self cleaning kitchen", b: "Self folding laundry", category: "Casual", difficulty: 2 },

    /* ---------- Workplace (18) ---------- */
    { text: "Would you rather have every meeting start on time or every meeting end ten minutes early?", a: "Meetings start on time", b: "Ten minutes handed back", category: "Workplace", difficulty: 1 },
    { text: "Would you rather have no email for a whole week or no meetings for a whole week?", a: "No email", b: "No meetings", category: "Workplace", difficulty: 2 },
    { text: "Would you rather work from home every day or from the office every day?", a: "Home every day", b: "Office every day", category: "Workplace", difficulty: 3 },
    { text: "Would you rather have video that never freezes or a mute button that never sticks?", a: "Video never freezes", b: "Mute always works", category: "Workplace", difficulty: 1 },
    { text: "Would you rather join every standup from a quiet beach or from a mountain cabin?", a: "Standup from a beach", b: "Standup from a cabin", category: "Workplace", difficulty: 2 },
    { text: "Would you rather have one long meeting a week or five short meetings a week?", a: "One long meeting", b: "Five short meetings", category: "Workplace", difficulty: 3 },
    { text: "Would you rather have an office kitchen that always has snacks or a coffee machine that never breaks?", a: "Snacks always stocked", b: "Coffee machine that works", category: "Workplace", difficulty: 1 },
    { text: "Would you rather have your calendar block its own focus time or your inbox sort itself perfectly?", a: "Automatic focus time", b: "Self sorting inbox", category: "Workplace", difficulty: 2 },
    { text: "Would you rather present to a big room with your notes or to a small group with no notes?", a: "Big room, with notes", b: "Small group, no notes", category: "Workplace", difficulty: 3 },
    { text: "Would you rather find any document in one click or have every file named clearly forever?", a: "One click documents", b: "Clear file names", category: "Workplace", difficulty: 1 },
    { text: "Would you rather have a deadline pushed back one week or the scope cut in half?", a: "One extra week", b: "Half the scope", category: "Workplace", difficulty: 2 },
    { text: "Would you rather keep your camera on for every call or type instead of speaking on every call?", a: "Camera always on", b: "Type, never speak", category: "Workplace", difficulty: 3 },
    { text: "Would you rather get a clear agenda before every meeting or clear notes after every meeting?", a: "Agenda before", b: "Notes after", category: "Workplace", difficulty: 1 },
    { text: "Would you rather sit at a quiet desk by a window or a busy desk right next to the coffee?", a: "Quiet window desk", b: "Busy desk near coffee", category: "Workplace", difficulty: 2 },
    { text: "Would you rather reply to messages within an hour or save them all for one block each day?", a: "Reply within the hour", b: "One reply block a day", category: "Workplace", difficulty: 2 },
    { text: "Would you rather have unlimited whiteboards or unlimited sticky notes?", a: "Unlimited whiteboards", b: "Unlimited sticky notes", category: "Workplace", difficulty: 1 },
    { text: "Would you rather have a keyboard that never needs cleaning or a screen that never smudges?", a: "Spotless keyboard", b: "Spotless screen", category: "Workplace", difficulty: 2 },
    { text: "Would you rather start at 6am and finish at 2pm or start at 11am and finish at 7pm?", a: "Early start, early finish", b: "Late start, late finish", category: "Workplace", difficulty: 3 },

    /* ---------- Cultural (12) ---------- */
    { text: "Would you rather have a lifetime supply of biryani or a lifetime supply of dumplings?", a: "Lifetime of biryani", b: "Lifetime of dumplings", category: "Cultural", difficulty: 2 },
    { text: "Would you rather spend Diwali in Sydney or Christmas in Manila?", a: "Diwali in Sydney", b: "Christmas in Manila", category: "Cultural", difficulty: 3 },
    { text: "Would you rather never miss a Sydney train again or never sit in Gurugram traffic again?", a: "Never miss a train", b: "Never stuck in traffic", category: "Cultural", difficulty: 1 },
    { text: "Would you rather eat Delhi street food every week or Singapore hawker food every week?", a: "Delhi street food", b: "Singapore hawker food", category: "Cultural", difficulty: 2 },
    { text: "Would you rather have masala dosa every morning or avocado toast every morning?", a: "Masala dosa", b: "Avocado toast", category: "Cultural", difficulty: 1 },
    { text: "Would you rather watch Lunar New Year fireworks in person or Sydney harbour fireworks in person?", a: "Lunar New Year fireworks", b: "Sydney harbour fireworks", category: "Cultural", difficulty: 3 },
    { text: "Would you rather take a long weekend in Goa or a long weekend in Palawan?", a: "Long weekend in Goa", b: "Long weekend in Palawan", category: "Cultural", difficulty: 2 },
    { text: "Would you rather drink filter coffee every afternoon or bubble tea every afternoon?", a: "Filter coffee", b: "Bubble tea", category: "Cultural", difficulty: 1 },
    { text: "Would you rather join a big three day wedding or a quiet beach picnic with a few friends?", a: "Three day wedding", b: "Quiet beach picnic", category: "Cultural", difficulty: 2 },
    { text: "Would you rather learn to cook adobo perfectly or learn to pull noodles by hand perfectly?", a: "Perfect adobo", b: "Perfect hand pulled noodles", category: "Cultural", difficulty: 3 },
    { text: "Would you rather spend a summer day at Bondi Beach or a monsoon evening in Mumbai?", a: "Bondi in summer", b: "Mumbai in the rain", category: "Cultural", difficulty: 1 },
    { text: "Would you rather throw colours at a Holi party or carry lanterns at a mid autumn night?", a: "Holi colour party", b: "Mid autumn lantern night", category: "Cultural", difficulty: 2 },
  ], [
    { key: "text", label: "Full question", type: "textarea", required: true },
    { key: "a", label: "Option A (short)", type: "text", required: true },
    { key: "b", label: "Option B (short)", type: "text", required: true },
  ]);
})();
